wordpress:
    image: wordpress:4.7.2-php7.1-fpm-alpine
    links:
     - mariadb:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=wordpress
    ports:
     - 80"
    volumes:
     - /var/www/html
mariadb:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=wordpress
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./database:/var/lib/mysql
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - mariadb:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: wordpress