wordpress:
  image: wordpress:4.7.2-php7.1-fpm-alpine
  depends_on:
  - db
  links:
  - db:mysql
  ports:
  - 80/tcp
  restart: always
  environment:
    WORDPRESS_DB_HOST: db:3306
    WORDPRESS_DB_PASSWORD: wordpress
db:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: wordpress
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress