master:
  build: .
  container_name: jenkins
  restart: unless-stopped
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true"
  ports:
    - "50000:50000"
    - "8080:8080"
  volumes:
    - /usr/local/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock
    - ${pwd}/JENKINS_HOME:/var/jenkins_home
