master:
  image: docker.bintray.io/jfrog/artifactory-oss:latest
  container_name: artifactory
  restart: unless-stopped
  ports:
    - "8081:8081"
  volumes:
    - ./artifactory-volume/data:/var/opt/jfrog/artifactory/data
    - ./artifactory-volume/logs:/var/opt/jfrog/artifactory/logs
    - ./artifactory-volume/etc:/var/opt/jfrog/artifactory/etc
